// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getMLE
RcppExport SEXP getMLE(SEXP mtx, SEXP steps, SEXP epsilon);
RcppExport SEXP gbra_getMLE(SEXP mtxSEXP, SEXP stepsSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type mtx(mtxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type epsilon(epsilonSEXP);
    __result = Rcpp::wrap(getMLE(mtx, steps, epsilon));
    return __result;
END_RCPP
}
// spearmanDist
RcppExport SEXP spearmanDist(SEXP mtx);
RcppExport SEXP gbra_spearmanDist(SEXP mtxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type mtx(mtxSEXP);
    __result = Rcpp::wrap(spearmanDist(mtx));
    return __result;
END_RCPP
}
