# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMLE <- function(mtx, steps, epsilon) {
    .Call('gbra_getMLE', PACKAGE = 'gbra', mtx, steps, epsilon)
}

spearmanDist <- function(mtx) {
    .Call('gbra_spearmanDist', PACKAGE = 'gbra', mtx)
}

